remote_theme: "mmistakes/minimal-mistakes@4.9.0"
minimal_mistakes_skin: "sunrise"

title: Show or Hide All Apps
description: A small Mac application to show or hide all applications on your desktop. It helps you cleaning up your desktop, and it's handy for very busy people with many opened windows.

author:
  name: "garraflavatra"
  avatar: "https://avatars.githubusercontent.com/u/34036573"
  email: "romein@vburen.eu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:romein@vburen.eu"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://garraflavatra.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/garraflavatra/show-hide-apps"

plugins:
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/garraflavatra/show-hide-apps"
